_wandb:
    value:
        cli_version: 0.21.0
        e:
            58h4gz0hu04reho4w3vltn21nl9wdsor:
                codePath: Hierarchical_Inference_and_Closure_Learning/poisson/train_PINNs.py
                codePathLocal: train_PINNs.py
                cpu_count: 16
                cpu_count_logical: 32
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1966447288320"
                        used: "1489582080000"
                email: pz281@cam.ac.uk
                executable: /home/pz/anaconda3/envs/jax/bin/python
                git:
                    commit: 924c93f5dd0d26646e5e836f458a1578eeb8347d
                    remote: git@github.com:ypzpy/Model_Discrepancy.git
                gpu: NVIDIA GeForce RTX 3090
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 10496
                      memoryTotal: "25769803776"
                      name: NVIDIA GeForce RTX 3090
                      uuid: GPU-0d3531fd-cd9b-fe3c-e6fb-2a192e6bbb7d
                host: csic40
                memory:
                    total: "134986268672"
                os: Linux-6.8.0-87-generic-x86_64-with-glibc2.35
                program: /home/pz/Documents/model_discrepancy/Hierarchical_Inference_and_Closure_Learning/poisson/train_PINNs.py
                python: CPython 3.11.11
                root: /home/pz/Documents/model_discrepancy/Hierarchical_Inference_and_Closure_Learning/poisson
                startedAt: "2026-03-02T22:07:29.192456Z"
                writerId: 58h4gz0hu04reho4w3vltn21nl9wdsor
        m: []
        python_version: 3.11.11
        t:
            "1":
                - 12
                - 45
            "2":
                - 12
                - 45
            "3":
                - 13
                - 16
                - 61
                - 62
            "4": 3.11.11
            "5": 0.21.0
            "12": 0.21.0
            "13": linux-x86_64
data_systems:
    value: namespace(rng_key=25, n_systems=20, nx=50, ny=50, L_x=1.0, L_y=1.0, obser_noise=0.1, obser_fraction=0.024, no_parameters=3)
hyperprior:
    value: namespace(mean=namespace(hyperprior_z1_prior=0.0, hyperprior_z2_prior=0.2, hyperprior_z3_prior=-0.1, hyperprior_mean_tau_z=0.4), variance=namespace(hyperprior_variance_mu_z1=0.2, hyperprior_variance_tau_z1=0.1, hyperprior_variance_mu_z2=0.2, hyperprior_variance_tau_z2=0.1, hyperprior_variance_mu_z3=0.2, hyperprior_variance_tau_z3=0.1))
langevin_sampler:
    value: namespace(n_samples=1, n_chains=160, batch_num=4, step_size=0.01, accept_ratio=0.574, step_size_lr=0.005, damping_param=10)
models:
    value: namespace(mlp_alpha=namespace(hidden_features=[64, 64, 64, 64], output_features=1, learning_rate=0.0003, n_decay_steps=1000, decay_rate=0.8), pinn_beta=namespace(layers=[5, 64, 64, 64, 64, 64, 1], learning_rate=0.0003, n_decay_steps=2000, decay_rate=0.8, opt_type='adam', weight_decay=0.001, fno_steps=20))
true_parameters:
    value: namespace(hyperprior_z1=0.2, hyperprior_z2=-0.1, hyperprior_z3=0.2, tau_phi_z1=0.5, tau_phi_z2=0.5, tau_phi_z3=0.5)
wandb:
    value: namespace(entity='pz281-university-of-cambridge', project='Bilevel Optimisation', run_name='poisson', group='poisson PINNs')
